{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $no_wrapper=true() }
{default $pdf_size='A4'
		 $pdf_orientation='portrait' }
{node_view_gui view=pdf content_node=$node
                         viewmode=$viewmode
                         language_code=$language_code
                         view_parameters=$view_parameters
                         collection_attributes=$collection_attributes
                         validation=$validation
                         persistent_variable=$persistent_variable
						 pdf_size=$pdf_size
						 pdf_orientation=$pdf_orientation}