{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default $pdf_size='A4'
		 $pdf_orientation='portrait' }
{ezpagedata_set('pdf_size', $pdf_size)}
{ezpagedata_set('pdf_orientation', $pdf_orientation)}
{node_view_gui view=full content_node=$node
                         viewmode=$viewmode
                         language_code=$language_code
                         view_parameters=$view_parameters
                         collection_attributes=$collection_attributes
                         validation=$validation
                         persistent_variable=$persistent_variable
						 pdf=true()
						 pdf_size=$pdf_size
						 pdf_orientation=$pdf_orientation}