{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $base_uri=concat( '/newsletter/register_subscription/', $subscriptionList.url_alias )}

<div class="box">
<div class="tl"><div class="tr"><div class="br"><div class="bl"><div class="box-content float-break">

<div class="content-view-full">
    <div class="class-folder">


        <div class="attribute-header">
            <h1>{$subscriptionList.name|wash} - {'Register subscription'|i18n( 'design/eznewsletter/register_subscription' )}</h1>
        </div>
        
        {if $subscriptionList.description|trim|ne('')}
            <p class="subscription-description">{$subscriptionList.description|wash}</p>
        {/if}
        <p class="subscription-description">Your email is safe with us. We won't ever give your email address to anyone else.</p>

{if $warning}
    <div class="message-warning">
        <h3>{$warning|wash}</h3>
    </div>
{/if}

<form name="subscription_list" method="post" action={$base_uri|ezurl}>

    {* First name. *}
    {if and( ezini_hasvariable('NewsletterSettings', 'AskForFirstName', 'sbase.ini'), ezini('NewsletterSettings', 'AskForFirstName', 'sbase.ini')|ne('enabled') )}
        <input type="hidden" name="Firstname" value="{cond( is_set( $user), $user.contentobject.data_map.first_name.content, $firstname)|wash}" />
    {else}
        <div class="block">
            <label>{"First name"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
            <input class="halfbox" id="subscriptionFirstname" type="text" name="Firstname" value="{cond( is_set( $user), $user.contentobject.data_map.first_name.content, $firstname)|wash}" title="{'First name of the subscriber.'|i18n( 'design/eznewsletter/register_subscription' )}"
                   {cond( is_set( $user ), 'disabled="disabled"', '')} />
        </div>
    {/if}

    {* Last name. *}
    {if and( ezini_hasvariable('NewsletterSettings', 'AskForLastName', 'sbase.ini'), ezini('NewsletterSettings', 'AskForLastName', 'sbase.ini')|ne('enabled') )}
        <input type="hidden" name="Name" value="{cond( is_set( $user), $user.contentobject.data_map.last_name.content, $name)|wash}" />
    {else}
        <div class="block">
            <label>{"Last name"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
            <input class="halfbox" id="subscriptionName" type="text" name="Name" value="{cond( is_set( $user ), $user.contentobject.data_map.last_name.content, $name)|wash}" title="{'Last name of the subscriber.'|i18n( 'design/eznewsletter/register_subscription' )}"
                   {cond( is_set( $user ), 'disabled="disabled"', '')} />
        </div>
    {/if}

    {* Mobile. *}
    {if and( ezini_hasvariable('NewsletterSettings', 'AskForMobile', 'sbase.ini'), ezini('NewsletterSettings', 'AskForMobile', 'sbase.ini')|ne('enabled') )}
        <input type="hidden" name="Mobile" value="{cond( is_set( $user), $user.$mobile, $mobile)|wash}" />
    {else}
        <div class="block">
            <label>{"Mobile number"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
            <input class="halfbox" id="subscriptionMoile" type="text" name="Mobile" value="{cond( is_set( $user ), $user.$mobile, $mobile)|wash}" title="{'Mobile number of the subscriber.'|i18n( 'design/eznewsletter/register_subscription' )}"
                   {cond( is_set( $user ), 'readonly="readonly"', '')} />
        </div>
    {/if}

    {* Email. *}
    <div class="block">
        <label>{"Email"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
        <input class="halfbox" id="subscriptionEmail" type="text" name="Email" value="{cond( is_set( $user ), $user.email, $email)|wash}" title="{'Email of the subscriber.'|i18n( 'design/eznewsletter/register_subscription' )}"
               {cond( is_set( $user ), 'disabled="disabled"', '')} />
    </div>

    {if $subscriptionList.require_password}
        {* Password. *}
        <div class="block">
            <label>{"Password"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
            <input name="Password1" size="25" type="password" value="password" {cond( is_set( $user ), 'readonly="readonly"', '' )} />
            <input name="Password2" size="25" type="password" value="password" {cond( is_set( $user ), 'readonly="readonly"', '' )} />
        </div>
    {/if}

    {if $output_map}
        {def $allowed_formats=array(0,1,2,3,4,5,6)
             $default_format=2}
        {if ezini_hasvariable('NewsletterSettings', 'AllowedOutputFormats', 'sbase.ini')}
            {set $allowed_formats=ezini('NewsletterSettings', 'AllowedOutputFormats', 'sbase.ini') }
        {/if}
        {if ezini_hasvariable('NewsletterSettings', 'DefaultOutputFormat', 'sbase.ini')}
            {set $default_format=ezini('NewsletterSettings', 'DefaultOutputFormat', 'sbase.ini') }
        {/if}
        <div class="block">
            <label>{"Output format"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
           {* <select name="OutputFormat[]" multiple="multiple" title="{'Output format'|i18n( 'design/eznewsletter/register_subscription' )}"> *}
            {foreach $output_map as $value => $out_name}
                {if $allowed_formats|contains($value)}
                    <input id="OutputFormat_{$value|wash}" name="OutputFormat[]" type="checkbox" value="{$value|wash}" {cond( eq($value, $default_format), 'checked="checked"', '')} title="{'Output format'|i18n( 'design/eznewsletter/register_subscription' )}">&nbsp;<label style="display:inline; font-weight:normal;" for="OutputFormat_{$value|wash}">{$out_name|wash}</label><br />
                    {*<option value="{$value|wash}" {cond( eq($value, $default_format), 'selected="selected"', '')}>{$out_name|wash}</option> *}
                {/if}
            {/foreach}
        {* </select> *}
    </div>
    {/if}

    <div class="block">
        <input class="button" type="submit" name="StoreButton" value="{'Subscribe'|i18n( 'design/eznewsletter/register_subscription' )}" title="{'Add to subscription.'|i18n( 'design/eznewsletter/register_subscription' )}" />
    </div>

</form>

    </div>
</div>

</div></div></div></div></div>
</div>
