{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - edit newslettertype *}

<div class="context-block">
{* DESIGN: Header START *}

<div class="box">
<div class="tl">
<div class="tr">
<div class="br">
<div class="bl">
<div class="box-content float-break">

<h1 class="context-title">{'Your settings'|i18n( 'design/eznewsletter/user_settings_profile' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>
{* DESIGN: Header END *}
{* DESIGN: Content START *}

<div class="context-attributes">

{if is_set($warning)}
    <div class="message-warning">
        <h3>{$warning|wash}</h3>
    </div>
{/if}

{* First name. *}
{if and( ezini_hasvariable('NewsletterSettings', 'AskForFirstName', 'sbase.ini'), ezini('NewsletterSettings', 'AskForFirstName', 'sbase.ini')|ne('enabled') )}
    <input id="subscriptionFirstname" type="hidden" name="FirstName" value="{$userData.firstname|wash}" />
{else}
    <div class="block">
        <label>{"First name"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
        <input id="subscriptionFirstname" class="halfbox" type="text" name="FirstName" value="{$userData.firstname|wash}" title="{'First name of the subscriber.'|i18n( 'design/eznewsletter/register_subscription' )}" />
    </div>
{/if}

{* Last name. *}
{if and( ezini_hasvariable('NewsletterSettings', 'AskForLastName', 'sbase.ini'), ezini('NewsletterSettings', 'AskForLastName', 'sbase.ini')|ne('enabled') )}
    <input id="subscriptionName" type="hidden" name="Name" value="{$userData.name|wash}" />
{else}
    <div class="block">
        <label>{"Last name"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
        <input class="halfbox" id="subscriptionName" type="text" name="Name" value="{$userData.name|wash}" title="{'Last name of the subscriber.'|i18n( 'design/eznewsletter/register_subscription' )}" />
    </div>
{/if}

{* Mobile. *}
{if and( ezini_hasvariable('NewsletterSettings', 'AskForMobile', 'sbase.ini'), ezini('NewsletterSettings', 'AskForMobile', 'sbase.ini')|ne('enabled') )}
    <input id="subscriptionMoile" type="hidden" name="Mobile" value="{$userData.mobile|wash}" />
{else}
    <div class="block">
        <label>{"Mobile number"|i18n( 'design/eznewsletter/register_subscription' )}:</label>
        <input class="halfbox" id="subscriptionMoile" type="text" name="Mobile" value="{$userData.mobile|wash}" title="{'Mobile number of the subscriber.'|i18n( 'design/eznewsletter/register_subscription' )}" />
    </div>
{/if}

<div class="block">
<label>{'Email'|i18n( 'design/eznewsletter/user_settings_profile' )}:</label>
<input class="halfbox" id="email" type="text" name="Email" value="{$userData.email|wash}" />
</div>
    
{* Password. *}

{if $userData.password}
    <div class="block">
        <label>{"Password"|i18n( 'design/eznewsletter/user_settings_profile' )}:</label>
        <input name="Password1" size="25" type="password" value="password" />
        <input name="Password2" size="25" type="password" value="password" />
    </div>
{/if}

{* TODO : PASSWORD *}

{* DESIGN: Content END *}</div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}
<div class="block">
    <input class="button" type="submit" name="UpdateSubscriptions" value="{'Update'|i18n( 'design/eznewsletter/user_settings_profile' )}" title="{'Update settings.'|i18n( 'design/eznewsletter/user_settings_profile' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
